logging:
  level:
    root: error
#    com.xh: error
spring:
  datasource:
    mysql:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1.com:3306/data_warehouse?characterEncoding=utf8&amp;useSSL=false&amp;autoReconnect=true&amp;failOverReadOnly=false
      username: root
      password: 1234
      initialSize: 5
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
    impala:
      driverClassName: com.cloudera.impala.jdbc41.Driver
#      jdbc-url: jdbc:impala://dw2.hb.com:21050/brms;auth=noSasl
#      jdbc-url: jdbc:impala://192.168.30.11:25004/brms;auth=noSasl
#      jdbc-url: jdbc:impala://192.168.30.11:21050/brms;auth=noSasl
      jdbc-url: jdbc:impala://172.20.0.207:21050/fintech;auth=noSasl





